.PHONY: clean All

All:
	@echo "----------Building project:[ string_functions - Debug ]----------"
	@cd "string_functions" && "$(MAKE)" -f  "string_functions.mk"
clean:
	@echo "----------Cleaning project:[ string_functions - Debug ]----------"
	@cd "string_functions" && "$(MAKE)" -f  "string_functions.mk" clean
