.PHONY: clean All

All:
	@echo "----------Building project:[ string_functions_2 - Debug ]----------"
	@cd "string_functions_2" && "$(MAKE)" -f  "string_functions_2.mk"
clean:
	@echo "----------Cleaning project:[ string_functions_2 - Debug ]----------"
	@cd "string_functions_2" && "$(MAKE)" -f  "string_functions_2.mk" clean
