.PHONY: clean All

All:
	@echo "----------Building project:[ P2.1 - Debug ]----------"
	@cd "P2.1" && "$(MAKE)" -f  "P2.1.mk"
clean:
	@echo "----------Cleaning project:[ P2.1 - Debug ]----------"
	@cd "P2.1" && "$(MAKE)" -f  "P2.1.mk" clean
