.PHONY: clean All

All:
	@echo "----------Building project:[ test_2 - Debug ]----------"
	@cd "test_2" && "$(MAKE)" -f  "test_2.mk"
clean:
	@echo "----------Cleaning project:[ test_2 - Debug ]----------"
	@cd "test_2" && "$(MAKE)" -f  "test_2.mk" clean
