.PHONY: clean All

All:
	@echo "----------Building project:[ 2d_array - Debug ]----------"
	@cd "2d_array" && "$(MAKE)" -f  "2d_array.mk"
clean:
	@echo "----------Cleaning project:[ 2d_array - Debug ]----------"
	@cd "2d_array" && "$(MAKE)" -f  "2d_array.mk" clean
