.PHONY: clean All

All:
	@echo "----------Building project:[ quiz_code - Debug ]----------"
	@cd "quiz_code" && "$(MAKE)" -f  "quiz_code.mk"
clean:
	@echo "----------Cleaning project:[ quiz_code - Debug ]----------"
	@cd "quiz_code" && "$(MAKE)" -f  "quiz_code.mk" clean
