.PHONY: clean All

All:
	@echo "----------Building project:[ func_2 - Debug ]----------"
	@cd "func_2" && "$(MAKE)" -f  "func_2.mk"
clean:
	@echo "----------Cleaning project:[ func_2 - Debug ]----------"
	@cd "func_2" && "$(MAKE)" -f  "func_2.mk" clean
